version: '2.2'
services:
  service04:
    image: bsquarelab/upost-service04:0.1
    container_name: service04
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./service04/data/tilon:/data/tilon
      - ./service04/data/POSA:/data/POSA
      - ./service04/exec/IljariAgent:/usr/share/tilon/IljariAgent
      - ./service04/exec/sender:/usr/share/tilon/sender
      - /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "1422:22"
    networks:
      - nmailbox

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge