version: '2.2'
services:
  goenv:
    image: bsquarelab/upost-goenv
    container_name: goenv
    volumes:
      - ./GoEnv/go:/go/upost
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    networks:
      - nmailbox

volumes:
  data01:
    driver: local

networks:
  nmailbox:
    driver: bridge