version: '2.2'
services:
  emailbox:
    image: mariadb:10.2.8
    #image: bsquarelab/upost-mariadb
    container_name: emailbox
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3307:3306
      - 3306:3306    
    volumes:
      - ./DB-Service01/mysql:/etc/mysql
      - ./DB-Service01/mariadb:/data/mysql
      - ./DB-Service01/data/analyzer/result:/data/tilon/analyzer/result
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - nmailbox    

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge