version: '2.2'
services:
  mailbox:
    image: bsquarelab/upost-node-mailbox:0.1
    container_name: mailbox
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./API-WAS1/docker-mailbox/mailbox/configs:/home/blab/mailbox/configs
      - ./API-WAS1/docker-mailbox/mailbox/public:/home/blab/mailbox/public
      - ./API-WAS1/docker-mailbox/mailbox/public_user:/home/blab/mailbox/public_user
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 8080:8080
    networks:
      - nmailbox
    command: npm run start.d

  static:
    image: bsquarelab/upost-node-static:0.1
    container_name: static
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./API-WAS1/data/storage:/home/blab/static/storage
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 8081:8081
    networks:
      - nmailbox


volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge
