version: '2.2'
services:
  node01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: node01
    environment:
      - node.name=node-1
#      - ELASTIC_USERNAME=admin
#      - ELASTIC_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Service03/config:/usr/share/elasticsearch/config
      - ./Service03/node01:/data/elasticsearch
      - ./Service03/log01:/var/log/elasticsearch
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 9200:9200
    networks:
      - nmailbox

  node02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
    container_name: node02
    environment:
      - node.name=node-2
#      - ELASTIC_USERNAME=admin
#      - ELASTIC_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Service04/config:/usr/share/elasticsearch/config
      - ./Service04/node02:/data/elasticsearch
      - ./Service04/log02:/var/log/elasticsearch
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    networks:
      - nmailbox

  kib01:
    image: docker.elastic.co/kibana/kibana:6.8.23
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://node01:9200
      ELASTICSEARCH_HOSTS: '["http://node01:9200","http://node02:9200"]'
    volumes:
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    depends_on:
      - node01
      - node02
    networks:
      - nmailbox
      
volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge