version: '2.2'
services:
  service01:
    image: bsquarelab/upost-service01:0.1
    container_name: service01
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./Service01/exec/interface:/usr/share/tilon/interface
      - ./Service01/exec/usrlocalbin:/usr/local/bin
      - ./Service01/exec/interface/res/mailbox/read/11001/60002/11001-60002-sample:/tmp/11001-60002-sample
      - ./Service01/exec/interface/res/mailbox/read/11001/60002/11001-60002-00003:/tmp/11001-60002-00003
      - ./Service01/exec/interface/res/mailbox/read/11002/60003/11002-60003-sample:/tmp/11002-60003-sample
      - ./Service01/exec/interface/res/mailbox/read/49757/69999/49757-69999-40001:/tmp/49757-69999-40001
      - ./Service01/exec/interface/res/mailbox/read/51001/60004/51001-60004-sample:/tmp/51001-60004-sample
      - ./Service01/exec/interface/res/mailbox/read/90001/60001/90001-60001-90001:/tmp/90001-60001-90001
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 2100:2100
      - "1222:22"
    depends_on:
      - external
    extra_hosts:
      - "mockup-edocdistcerfgw.epost.go.kr:211.253.86.102"
      - "dev-edocdistcertgw.epost.go.kr:211.253.86.102"
      - "edocdistcdertgw.epost.go.kr:211.253.86.102"
    networks:
      - nmailbox

  service02:
    image: bsquarelab/upost-service02:0.1
    container_name: service02
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./Service02/exec/collector:/usr/share/tilon/collector
      - ./Service02/exec/interface:/usr/share/tilon/interface
      - ./Service02/exec/pusher:/usr/share/tilon/pusher
      - ./Service02/exec/usrlocalbin:/usr/local/bin
      - ./Service01/exec/interface/res/mailbox/read/11001/60002/11001-60002-sample:/tmp/11001-60002-sample
      - ./Service01/exec/interface/res/mailbox/read/11001/60002/11001-60002-00003:/tmp/11001-60002-00003
      - ./Service01/exec/interface/res/mailbox/read/11002/60003/11002-60003-sample:/tmp/11002-60003-sample
      - ./Service01/exec/interface/res/mailbox/read/49757/69999/49757-69999-40001:/tmp/49757-69999-40001
      - ./Service01/exec/interface/res/mailbox/read/51001/60004/51001-60004-sample:/tmp/51001-60004-sample
      - ./Service01/exec/interface/res/mailbox/read/90001/60001/90001-60001-90001:/tmp/90001-60001-90001
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 2101:2100
      - "2222:22"
    depends_on:
      - service01
    extra_hosts:
      - "mockup-edocdistcerfgw.epost.go.kr:211.253.86.102"
      - "dev-edocdistcertgw.epost.go.kr:211.253.86.102"
      - "edocdistcdertgw.epost.go.kr:211.253.86.102"
    networks:
      - nmailbox

  service04:
    image: bsquarelab/upost-service04:0.3
    container_name: service04
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./Service04/data/tilon:/data/tilon
      - ./Service04/data/blab:/data/blab
      - ./Service04/data/POSA:/data/POSA
      - ./Service04/exec/IljariAgent:/usr/share/tilon/IljariAgent
      - ./Service04/exec/sender:/usr/share/tilon/sender
      - ./Service04/exec/CollectAgent:/usr/share/blab/CollectAgent
      - ./Service04/exec/SyncAgent:/usr/share/blab/SyncAgent
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "4222:22"
      - 3001:3001
      - 3002:3002
    depends_on:
      - service02
    extra_hosts:
      - "mockup-edocdistcerfgw.epost.go.kr:211.253.86.102"
      - "dev-edocdistcertgw.epost.go.kr:211.253.86.102"
      - "edocdistcdertgw.epost.go.kr:211.253.86.102"
    networks:
      - nmailbox

  dbservice01:
    image: bsquarelab/upost-dbservice01:0.2
    container_name: dbservice01
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./DB-Service01/data:/data/tilon
      - ./DB-Service01/exec/analyzer:/usr/share/tilon/analyzer
      - ./DB-Service01/exec/analyzer.authorized:/usr/share/tilon/analyzer.authorized
      - ./DB-Service01/exec/sender:/usr/share/tilon/sender
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "1333:22"
    depends_on:
      - service04
    extra_hosts:
      - "mockup-edocdistcerfgw.epost.go.kr:211.253.86.102"
      - "dev-edocdistcertgw.epost.go.kr:211.253.86.102"
      - "edocdistcdertgw.epost.go.kr:211.253.86.102"
    networks:
      - nmailbox

  external:
    image: bsquarelab/upost-external:0.1
    container_name: external
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./External01/data/11001:/11001
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "1555:22"
    extra_hosts:
      - "mockup-edocdistcerfgw.epost.go.kr:211.253.86.102"
      - "dev-edocdistcertgw.epost.go.kr:211.253.86.102"
      - "edocdistcdertgw.epost.go.kr:211.253.86.102"
    networks:
      - nmailbox

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge