version: '2.2'
services:
  postalk:
    image: bsquarelab/upost-node-postalk:0.1
    container_name: postalk
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./API-WAS1/docker-postalk/postalk/configs:/home/tilon/postalk/configs
      - ./API-WAS1/docker-postalk/postalk/public:/home/tilon/postalk/public
      - ./API-WAS1/docker-postalk/postalk/public_user:/home/tilon/postalk/public_user
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 8880:8080
    networks:
      - nmailbox
    command: npm test

  postalk-front:
    image: bsquarelab/upost-node-postalk-front:0.1
    container_name: postalk-front
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    stdin_open: true
    volumes:
      - ./API-WAS1/docker-postalk-front/postalk-front/src/config.js:/home/blab/postalk-front/src/config.js
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 3000:3000
    networks:
      - nmailbox
    command: npm start

  static:
    image: bsquarelab/upost-node-static:0.1
    container_name: static
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./API-WAS1/data/storage:/home/blab/static/storage
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 8881:8081
    networks:
      - nmailbox


volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge
