version: '2.2'
services:
  mailbox:
    image: bsquarelab/upost-node-mailbox:0.1
    container_name: mailbox
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./API-WAS1/docker-mailbox/mailbox/configs:/home/tilon/mailbox/configs
      - ./API-WAS1/docker-mailbox/mailbox/public:/home/tilon/mailbox/public
      - ./API-WAS1/docker-mailbox/mailbox/public_user:/home/tilon/mailbox/public_user
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 8080:8080
    extra_hosts:
      - "emailbox:172.27.0.23"
      - "node01:172.27.0.23"
      - "service01:172.27.0.22"
      - "service02:172.27.0.22"
      - "service03:172.27.0.21"
      - "service04:172.27.0.21"
      - "mockup-edocdistcerfgw.epost.go.kr:172.27.0.24"
      - "dev-edocdistcertgw.epost.go.kr:172.27.0.24"
      - "edocdistcdertgw.epost.go.kr:172.27.0.24"
    networks:
      - nmailbox
    command: npm run start.d

  static:
    image: bsquarelab/upost-node-static:0.1
    container_name: static
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./API-WAS1/data/storage:/home/blab/static/storage
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 8081:8081
    networks:
      - nmailbox


volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge
