version: '2.2'
services:
  service01:
    image: bsquarelab/upost-service01:0.1
    container_name: service01
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./Service01/exec/interface:/usr/share/tilon/interface
      - ./Service01/exec/usrlocalbin:/usr/local/bin
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 2100:2100
      - "1122:22"
    depends_on:
      - external
    networks:
      - nmailbox

  service02:
    image: bsquarelab/upost-service02:0.1
    container_name: service02
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./Service02/exec/collector:/usr/share/tilon/collector
      - ./Service02/exec/interface:/usr/share/tilon/interface
      - ./Service02/exec/pusher:/usr/share/tilon/pusher
      - ./Service01/exec/usrlocalbin:/usr/local/bin
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - 2101:2100
      - "1222:22"
    depends_on:
      - service01
    networks:
      - nmailbox

  service04:
    image: bsquarelab/upost-service04:0.1
    container_name: service04
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./Service04/data/tilon:/data/tilon
      - ./Service04/data/POSA:/data/POSA
      - ./Service04/exec/IljariAgent:/usr/share/tilon/IljariAgent
      - ./Service04/exec/sender:/usr/share/tilon/sender
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "1422:22"
    depends_on:
      - service02
    networks:
      - nmailbox

  dbservice01:
    image: bsquarelab/upost-dbservice01:0.1
    container_name: dbservice01
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./DB-Service01/data:/data/tilon
      - ./DB-Service01/exec/analyzer:/usr/share/tilon/analyzer
      - ./DB-Service01/exec/sender:/usr/share/tilon/sender
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "2122:22"
    depends_on:
      - service04
    networks:
      - nmailbox

  external:
    image: bsquarelab/upost-external:0.1
    container_name: external
    environment:
      - TZ=Asia/Seoul
    restart: 'no'
    privileged: true
    volumes:
      - ./External01/data/11001:/11001
      - ${LOCALTIME}:/etc/localtime:ro
      #- /private/etc/localtime:/etc/localtime:ro
      #- /etc/localtime:/etc/localtime:ro #on linux
    ports:
      - "3122:22"
    networks:
      - nmailbox

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  nmailbox:
    driver: bridge