/******************************************************************************
			POSTOK Procedure Deletion
			version : 1.2.7
			
			Auth : HAEIN LEE
			Last Update Date : 2020-07-01
*******************************************************************************/
-- 48 PROCEDURES : 20.07.07
USE EMAILBOX;
DROP PROCEDURE IF EXISTS `SP_AN_GET_MEMBERFROMCI`;
DROP PROCEDURE IF EXISTS `SP_AN_GET_MEMBERFROMMI`;
DROP PROCEDURE IF EXISTS `SP_AN_GET_MEMBERFROMPI`;
DROP PROCEDURE IF EXISTS `SP_AN_GET_RECVADDRESS`;
DROP PROCEDURE IF EXISTS `SP_AN_GET_TEMPLATECODE`;
DROP PROCEDURE IF EXISTS `SP_AN_GET_VALIDITYAGENCY`;
DROP PROCEDURE IF EXISTS `SP_AN_REG_DOCUMENT`;
DROP PROCEDURE IF EXISTS `SP_AN_SET_STAT`;
DROP PROCEDURE IF EXISTS `SP_AUTH`;
DROP PROCEDURE IF EXISTS `SP_IF_DEL_ADDR`;
DROP PROCEDURE IF EXISTS `SP_IF_DEL_MYAGENCYADDRESS`;
DROP PROCEDURE IF EXISTS `SP_IF_DEL_MYDOCUMENT2`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_ADDRESS`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_AGENCY`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_CAR`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_MEMBER`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_MYAGENCY`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_MYDOCUMENT2`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_MYMESSAGE2`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_MYPAYMENT`;
DROP PROCEDURE IF EXISTS `SP_IF_GET_PCODE`;
DROP PROCEDURE IF EXISTS `SP_IF_LOGIN`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_ADDRESS`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_ADDRPICKUP`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_AFTER_AUTH`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CAR`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGEADDRESS`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGECAR`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGEMYAGENCY`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGEMYAGENCYRECVCLASS`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGEPASS`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGEPHONE`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_CHANGE_EMAIL`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_HISTORY_MYAGENCY_DISPCLASS`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_MESSAGEPERMISSION`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_MYAGENCY`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_MYAGENCYADDRESS`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_PCODE`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_PUSHTOKEN`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_SIGNOUT`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_SIGNUP`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_SIGNUP2`;
DROP PROCEDURE IF EXISTS `SP_IF_SET_SIGNUP3`;
DROP PROCEDURE IF EXISTS `SP_PAY_READY`;
DROP PROCEDURE IF EXISTS `SP_PAY_RESULT`;
DROP PROCEDURE IF EXISTS `SP_PS_GET_MESSAGE`;
DROP PROCEDURE IF EXISTS `SP_PS_SET_DISPATCHED`;
DROP PROCEDURE IF EXISTS `SP_PS_SET_ERROR`;
DROP PROCEDURE IF EXISTS `SP_IF_DEL_CAR`;
