---
  name: "pst.com-org1"
  x-type: "hlfv1"
  description: "pst.com-org1"
  version: "1.0"
  client: 
    organization: "org1"
    credentialStore: 
      path: "/data/workspace/pst/fabric-client-k-org1"
      cryptoStore: 
        path: "/data/workspace/pst/fabric-client-v-org1"
