---
  version: "2"
  services: 
    prometheus: 
      image: "prom/prometheus:v1.7.0"
      container_name: "mon-prometheus"
      volumes: 
        - "/data/workspace/pst/monitor/prometheus.yaml:/etc/prometheus/prometheus.yaml"
        - "/data/workspace/pst/monitor_data/prom_data:/prometheus"
      command: 
        - "-log.level=error"
        - "-config.file=/etc/prometheus/prometheus.yaml"
        - "-web.console.libraries=/etc/prometheus/console_libraries"
        - "-web.console.templates=/etc/prometheus/consoles"
        - "-storage.local.path=/prometheus"
      ports: 
        - "9090:9090"
      restart: "always"
      user: "root"
      networks: "pstnet1569336953"
    grafana: 
      image: "grafana/grafana"
      container_name: "mon-grafana"
      environment: 
        GF_SECURITY_ADMIN_USER: "admin"
        GF_SECURITY_ADMIN_PASSWORD: "pass"
      ports: 
        - "9080:3000"
      volumes: 
        - "/data/workspace/pst/monitor_data/grafana_data:/var/lib/grafana"
      depends_on: 
        - "prometheus"
      restart: "always"
      user: "root"
      networks: "pstnet1569336953"
