docker load < tar/fabric-tools-1.4.0.tar
docker load < tar/fabric-ccenv-1.4.0.tar
docker load < tar/fabric-orderer-1.4.0.tar
docker load < tar/fabric-peer-1.4.0.tar
docker load < tar/fabric-ca-1.4.0.tar
docker load < tar/fabric-zookeeper-0.4.14.tar
docker load < tar/fabric-kafka-0.4.14.tar
docker load < tar/fabric-couchdb-0.4.14.tar
docker load < tar/fabric-baseos-0.4.14.tar
